### ISSUE TITLE
String only as 0

### ISSUE THREAD

**Issue by JFP-SG** [grafana/mqtt-datasource#19]
Hello,

we are testing the Plugin now (with Grafana 8.1.1)
Values are interpreted correctly and easy JSON as well.
But this seems to be limited to Values (Float, ...), Strings are replaced by "0".

Also String in JSON payload gives error:
"error unmarshalling json message: json: cannot unmarshal string into Go value of type float64"

Is it planned to support Strings as well?

Thanks

**Comment by atifali** [comment]
yes - currently we only support very simple JSON structures, see: https://github.com/grafana/mqtt-datasource/issues/8#issuecomment-893981105

we do plan to support more complex JSON structures (which will include more data type support), and better support for timestamps. 

closing this now since it's related to: https://github.com/grafana/mqtt-datasource/issues/8
