### ISSUE TITLE
Streaming is not working? Have to manually refresh

### ISSUE THREAD

**Issue by victorclaessen** [grafana/mqtt-datasource#20]
Hi, from the animated GIF in the README I got the impression that a panel using the MQTT data would auto update as new data came in. I was hoping to use this to show my data at 10 Hz which the normal refresh method does not support.

However, for me, the panel does not auto update as in the README GIF. Do I have to activate that somewhere? I do to see all datapoints (10 are published each second) when I manually refresh or set the dashboard refresh to 1s. But then the whole dashboard updates at 1 Hz and it just fills in 10 datapoints at a time, and not 1 datapoint every 100ms, as I had hoped.

Do I have to activate streaming somewhere? Or am I missing something?

Grafana 8.1.1 on Debian 11, used the Ubuntu steps from the README to install the plugin. That seems to have worked at least.

**Comment by atifali** [comment]
can you provide some more details about your MQTT setup, as in the broker side and where the messages are being published on the topic etc? 

have you given the dummy MQTT test broker a try yet? its here: https://github.com/grafana/mqtt-datasource/blob/main/test_broker.js

you can run that but installing NodeJS and then running this from root of this repo:
```
node test_broker.js
```

**Comment by victorclaessen** [comment]
I'm currently using the EMQx broker. I'm publishing floats (via MQTT they are always in the form of strings, but **without quotes or other decoration**) on topic `FELIX/powermeter/shot/estimated_power`. With _MQTT Explorer_ or _mosquitto_sub_ I see the messages appearing. As mentioned, all the values show up when I refresh manually, so they are obviously arriving.

I am willing to try another broker, though I do not expect that to make a difference. However, that will have to wait two weeks due to holidays.

**Comment by atifali** [comment]
hmm - can you show me what the message looks like exactly? i think it has to do with how your message is formatted and is being received by the frontend. thank you for the details 🙂

**Comment by sommbeer** [comment]
Ok thank you. I got the same messages. It is not caused by MQTT, but by the HTTP Requests, performed by the Live panels. This HTTP request fails status exit code 403 (forbidden). This is because Grafana checks the Origin of the HTTP request to match the `root_url` value from the configuration.  
The issue is also described in the issue, I mentioned above.

So now you have 2 possibilities. You have to change a parameter in the Grafana configuration file. ( see the Docs https://grafana.com/docs/grafana/latest/administration/configuration/ )
- change the value of `root_url` in section `[server]`to "http://192.168.1.60:3000"
- add "http://192.168.1.60:3000" to the values of `allowed_origins` in section `[live]`

I have to say, that I am also not an expert in HTTP and am currently not 100% sure as there are also some other IP-addresses and localhost mentioned above. So if this does not work, you can maybe try a list of the options. Probably the easiest way is to use a wildcard, by setting `allowed_origins=*`. This should allow every origin, but surely is less secure.

**Comment by HenrikRolandHansen** [comment]
That did the trick thanks a lot.  :)

Now I only have to manage the MQTT topic that Grafana live don't seam to like due to spaces or Danish special letters eg æ, Ø Å. 

Invalid channel ID" logger=live user=1 client=adc1ca40-15a4-424d-a341-5afc7e234901 channel="1/ds/Y1apShRRk/VÃ¦relse mor

cheers

**Comment by victorclaessen** [comment]
Ok, back from holiday. Good to see a lot of activity on this issue.

Ok, so by now it seemed clear it was not a broker issue, but rather a web issue. I was not seeing any of the "Request Origin is not authorized" messages described above, so in my case that was not the problem.

While trying another browser (Chrome instead of Firefox) I noticed that I also had the same error messages in the console as linked from this https://github.com/grafana/mqtt-datasource/issues/20#issuecomment-905732491, i.e. _websocket connection failed_.

**I now realised there was an apache2 reverse proxy in between that was not handling the websocket connection right.** I am serving grafana in the virtual path /grafana on my server. This is the relevant piece of my apache2 configuration:

        # reverse proxy for grafana
        ProxyPass /grafana/ http://localhost:3000/
        ProxyPassReverse /grafana/ http://localhost:3000/
        Redirect        "/grafana"  "/grafana/"

Reading from https://github.com/grafana/grafana/issues/36929#issuecomment-901836732 **I managed to make it work by enabling mod_rewrite and adding these lines to the apache2 configuration**:

        RewriteEngine On
        RewriteCond %{HTTP:Upgrade} =websocket [NC]
        RewriteRule /grafana/(.*)           ws://localhost:3000/$1 [P,L]

Thanks to all for your help!
